### ISSUE TITLE
Expandable/ExpandableGroup prototypes focus issue

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#1161] opened 2015-11-20 22:02 UTC
The entire Expandable isn't highlighted when the element has the focus. 
Depicted in the following image : 

![image](https://cloud.githubusercontent.com/assets/1860176/11229219/39fedc92-8d61-11e5-86a3-fc55803e3b9a.png)

**Comment by anselmbradford** [comment] 2015-11-23 15:30
Technically the clickable area of the expandable is the area highlighted with the border, not the whole expandable. So when tabbing to the expandable the highlighted area shown is what would receive keyboard input, since that's the only area that responds to mouse clicks. I do agree it looks weird though. So does it matter if the border is not truly the active area, and instead is the whole expandable? Also, it seems like this highlighting should only appear on keyboard input, not on mouse clicks, right? cc @KimberlyMunoz

**Comment by KimberlyMunoz** [comment] 2015-11-23 20:02
The issue is more that it looks off. It can be fixed by either adding focus to the entire expandable or fixing the bottom focus.

**Comment by anselmbradford** [comment] 2018-02-13 15:21
Moved to https://github.com/cfpb/capital-framework/issues/760

**Closed by anselmbradford** 2018-02-13 15:21 UTC
Labels: bug
