### ISSUE TITLE
links formatted differently in FCM

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1335] opened 2016-01-13 01:33 UTC
in the featured content module, the content link and the optional additional links provided are formatted differently. we'd like them to be formatted the same. an example of this is here: /consumer-help/financial-resources-servicemembers/

**Comment by kurtw** [comment] 2016-01-13 20:36
Is this a duplicate of #1328

**Comment by KimberlyMunoz** [comment] 2016-01-28 15:33
We're going to tackle this issue in #1379

**Closed by KimberlyMunoz** 2016-01-28 15:33 UTC
Labels: wagtail-bug
