### ISSUE TITLE
download icon for pdfs missing from document detail template

### ISSUE THREAD

**Issue by sarahsimpson09** [cfpb/cfgov-refresh#1390] opened 2016-01-29 18:31 UTC

**Comment by schaferjh** [comment] 2016-01-29 19:17
Just want to note that in fact we want the download icon to show up automatically on any link for any document (PDF, DOCX, etc). If it can't be automatic, then we need some way for content editors to add it -- but would be preferable if the cms could recognize that the linked object is not a hyperlink and add the icon automatically.

For reference, this is the [Design Manual entry on hyperlinks] (https://cfpb.github.io/design-manual/ui-toolkit/links.html) -- scroll to the bottom for "Links with icons" section and see the download example.

**Comment by KimberlyMunoz** [comment] 2016-01-29 19:27
Do we want to limit what molecules the download icon is shown in? We've included a little bit of code on the WordPress "subpages" to do this and we can move it to some of the atomic stylesheets.
https://github.com/cfpb/cfgov-refresh/blob/5e64cc36be5d1e50c0815c1dcea6d1013a9ff344/cfgov/unprocessed/css/pages/sub-pages.less#L16

**Comment by schaferjh** [comment] 2016-02-01 16:09
Um, I think the only kinds of places where we wouldn't want the icon is in headers or navigation -- but that seems like the kind of thing we could control via content input. @duelj and @ajbush am I missing anything?

Also, I noticed that the download link isn't showing up on blog/news entries, which are being pulled in from WordPress -- _is that a different bug that I should log separately?_ Examples: [First link in body text of this post is a PDF](http://beta.consumerfinance.gov/blog/dont-be-a-zombie-with-your-personal-finances/) and [report link at the end of this post is a PDF](http://beta.consumerfinance.gov/blog/struggling-to-keep-up-with-student-loan-repayment-2/)

**Comment by duelj** [comment] 2016-02-01 17:05
@schaferjh - that sounds right to me. Although keeping the icon in **all** cases (including header and nav) might help us quickly sort if someone tries putting a download in on of those areas, and flag it earlier than if there were no icon. Sort of keeping a bug to spot another bug (improper use of content).

**Comment by KimberlyMunoz** [comment] 2016-02-01 20:22
> Also, I noticed that the download link isn't showing up on blog/news entries, which are being pulled in from WordPress -- is that a different bug that I should log separately?

Nope. Same issue.

> (PDF, DOCX, etc) 

What are the etc files... `.doc` is one, but do you have a full list?

**Comment by schaferjh** [comment] 2016-02-01 22:29
I don't have a full list, but I think this list would cover 95% (if not 99%) of instances:
* PDF
* DOCX
* DOC
* XLSX
* XLS
* CSV

@sarahsimpson09 @tnferrell anything you'd add?

**Comment by KimberlyMunoz** [comment] 2016-02-03 17:20
I got it working in a way that looks good with our mobile styles, works with our download lists, and doesn't do anything weird when there's already an icon. However, due to the new way we're doing underlines in CF, the icons have an underline that we won't be able to remove with CSS alone in full-width text molecules and the blog.

Thoughts on how to address this?

![image](https://cloud.githubusercontent.com/assets/1860176/12790442/45f8eef6-ca70-11e5-9968-69a0a668c80d.png)

**Comment by Scotchester** [comment] 2016-02-03 18:03
@KimberlyMunoz I did a lot of research back in the day, and I don't think it's possible with CSS only, unfortunately.

At one point, we had the notion to use Sheer to filter the content coming in from the CMS to add in the necessary markup to do this as designed when it detected a PDF link or external link. The same concept could probably be done with Django?

**Comment by KimberlyMunoz** [comment] 2016-02-03 18:16
Is this something that we can do, @kurtw, @kave or @richaagarwal?

Using this method, we could add a `<span class="cf-icon cf-icon-download"></span>`, but we'd have to do this in only the blog section and full-text width modules to prevent an extra download icon with list downloads.

![image](https://cloud.githubusercontent.com/assets/1860176/12792110/4597f684-ca78-11e5-8f96-ef2424b40756.png)

**Comment by kurtw** [comment] 2016-02-03 19:00
This is an interesting question. This is certainly possible to add a content type to select which would render the link like that, but within a RichTextField it could be rather hard. More research is needed, but I'll get an answer ASAP.

**Comment by schaferjh** [comment] 2016-02-03 19:16
Is this something that will apply to adding the external link icon to non-gov third party links as well?

**Comment by schaferjh** [comment] 2016-02-04 18:14
btw, in discussion with content we realized ZIP is also a file type that we should include as a linked file type that gets this icon.

**Comment by schaferjh** [comment] 2016-02-19 14:19
@KimberlyMunoz for V1 I am totally fine with the link underline continuing under the icon. @kurtw did your research turn up anything? If no or if the fix is time-consuming, I would like us to move forward with showing the icon with the link underline in some places.

This is high priority because users need to know if a link is a document or a hyperlink. It's also high priority if the answer to this:
> Is this something that will apply to adding the external link icon to non-gov third party links as well?

is yes.

**Comment by kurtw** [comment] 2016-03-02 15:23
Apologies for the late response. Unfortunately, the icon feature within rich text fields would be time consuming. Is @KimberlyMunoz solution sufficient for all cases? Meaning, is there anything else BEWDs could take care of or need to be aware?

**Comment by KimberlyMunoz** [comment] 2016-03-02 17:32
I'll take this issue for this sprint. We'll add a task for a better solution in v2.

**Comment by Scotchester** [comment] 2016-03-11 14:26
Something else that could impact this in v4 that you might want to note in your future task: a [move away from minicons as an icon font to an SVG library](https://github.com/cfpb/hackathon/issues/41).

**Comment by KimberlyMunoz** [comment] 2016-03-11 16:10
The implementation should still be similar. At the very least moving to SVGs will be a big move that affects everything at once and we'll know how to deal with it in this case.

**Closed** 2016-03-15 14:55 UTC
Labels: FEWD, priority: high
